### ISSUE TITLE
红米note7pro上无法打开，直接闪退

### ISSUE THREAD

**Issue by asky88** [newhying/AntiZhaPian#1]
如题 系统为安卓10 miui12.5.1

**Comment by newhying** [comment]
没办法哦，个人玩家，没有测试机，只有我的2个三星机和虚拟机。当然你可以试下之前的版本，因为程序越来越复杂，加的东西越来越多，或许前面的某个版本你可以用。我怀疑是不是因为对于水滴屏什么的处理导致的。如果发现之前某个版本可用，然后下个版本就不行了，你告诉我，我看有没有办法解决。
