### ISSUE TITLE
更新报告

### ISSUE THREAD

**Issue by bakeair** [newhying/AntiZhaPian#2]
资料页有变化了
![IMG_20230110_163729](https://user-images.githubusercontent.com/76464133/211501808-2890908d-db8c-419b-8d71-bc255fffb047.jpg)
![IMG_20230110_163641](https://user-images.githubusercontent.com/76464133/211501825-9e44eff9-57ca-41ed-905b-c31a069fd05b.jpg)

**Comment by newhying** [comment]
已更新
